- type: pointOfInterest
  id: BasePOI
  abstract: true
  minimumDistance: 2000 # Some sane defaults
  maximumDistance: 4000
  spawnGamePreset: [ NFAdventure, NFPirate, LuaAdventure ]
  spawnGroup: Optional
  addComponents:
  - type: IFF
    color: "#ffa600"
    readOnly: true
  # Prevent gravity changes
  - type: ForceAnchor
